// status
export const TOGGLE_TRACE_STATUS = 'TOGGLE_TRACE_STATUS';
export const TOGGLE_TRACE_STATUS_SUCCESS = 'TOGGLE_TRACE_STATUS_SUCCESS';
export const TOGGLE_TRACE_STATUS_ERROR = 'TOGGLE_TRACE_STATUS_ERROR';
export const SET_TRACE_STATUS = 'SET_TRACE_STATUS';

// navigation
export const QUERY_KEY_DOWN = 'QUERY_KEY_DOWN';
export const QUERY_INPUT_CHANGE = 'QUERY_INPUT_CHANGE';
export const CLEAR_FUNCTION_BROWSER = 'CLEAR_FUNCTION_BROWSER';
export const SET_POSITION = 'SET_POSITION';
export const FILL_AUTOCOMPLETER_MATCHES = 'FILL_AUTOCOMPLETER_MATCHES';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_TYPE = 'SET_TYPE';
export const SET_EXAMPLE = 'SET_EXAMPLE';
export const ADD_RECENT_QUERY = 'ADD_RECENT_QUERY';
export const SAVE_DIRTY_INPUT = 'SAVE_DIRTY_INPUT';
export const SWITCH_INPUT_TYPE = 'SWITCH_INPUT_TYPE';
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';

// monitoring
export const UPDATE_MONITORED_FUNCTIONS = 'UPDATE_MONITORED_FUNCTIONS';
export const UPDATE_DATA = 'UPDATE_DATA';
export const STOP_MONITORING_FUNCTION = 'STOP_MONITORING_FUNCTION';
export const STOP_MONITORING_FUNCTION_ERROR = 'STOP_MONITORING_FUNCTION_ERROR';
export const EXPAND_GRAPH_PANEL = 'EXPAND_GRAPH_PANEL';
export const SHRINK_GRAPH_PANEL = 'SHRINK_GRAPH_PANEL';
export const ASSIGN_GRAPH_ID = 'ASSIGN_GRAPH_ID';
export const CHANGE_SIZE = 'CHANGE_SIZE';

// tracing
export const UPDATE_CALLS = 'UPDATE_CALLS';
export const SET_CALLS_CONTROL = 'SET_CALLS_CONTROL';
export const SORT_CALLS = 'SORT_CALLS';
export const TOGGLE_EXPAND_ITEM = 'TOGGLE_EXPAND_ITEM';
export const EXPAND_TRACING_PANEL = 'EXPAND_TRACING_PANEL';
export const SHRINK_TRACING_PANEL = 'SHRINK_TRACING_PANEL';
export const SET_GRID = 'SET_GRID';

// explore
export const ADD_CALLEES = 'ADD_CALLEES';
export const SHOW_FUNCTIONS_CALLES = 'SHOW_FUNCTIONS_CALLES';
export const HIDE_FUNCTIONS_CALLES = 'HIDE_FUNCTIONS_CALLES';

// notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const LOST_CONNECTION = 'LOST_CONNECTION';
export const ALIVE_CONNECTION = 'ALIVE_CONNECTION';
export const HIDE_CONNECTION_NOTIFICATION = 'HIDE_CONNECTION_NOTIFICATION';
