// export const START_TRACING_FUNCTION = 'ADD_GRAPH';
// export const STOP_TRACING_FUNCTION = 'STOP_TRACING_FUNCTION';
// export const PAUSE_TRACING = 'PAUSE_TRACING';
// export const START_SLOW_CALLS_TRACING = 'START_SLOW_CALLS_TRACING';
// export const STOP_SLOW_CALLS_TRACING = 'STOP_SLOW_CALLS_TRACING';
// // ?
// export const CAPTURE_DATA = 'CAPTURE_DATA';
// export const CAPTURE_CALLS = 'CAPTURE_CALLS';

export const TOGGLE_TRACE_STATUS = 'TOGGLE_TRACE_STATUS';
export const TOGGLE_TRACE_STATUS_SUCCESS = 'TOGGLE_TRACE_STATUS_SUCCESS';
export const TOGGLE_TRACE_STATUS_ERROR = 'TOGGLE_TRACE_STATUS_ERROR';
export const QUERY_KEY_DOWN = 'QUERY_KEY_DOWN';
export const QUERY_INPUT_CHANGE = 'QUERY_INPUT_CHANGE';
export const CLEAR_FUNCTION_BROWSER = 'CLEAR_FUNCTION_BROWSER';
export const SET_POSITION = 'SET_POSITION';
export const FILL_AUTOCOMPLETER_FUNCTIONS = 'FILL_AUTOCOMPLETER_FUNCTIONS';
//
export const START_MONITORING_FUNCTION = 'START_MONITORING_FUNCTION';
export const SET_TRACE_STATUS = 'SET_TRACE_STATUS';
export const UPDATE_CAPTURE = 'UPDATE_CAPTURE';
export const UPDATE_MONITORED_FUNCTIONS = 'UPDATE_MONITORED_FUNCTIONS';
export const UPDATE_DATA = 'UPDATE_DATA';
