export const START_TRACING_FUNCTION = 'ADD_GRAPH';
export const STOP_TRACING_FUNCTION = 'STOP_TRACING_FUNCTION';
export const PAUSE_TRACING = 'PAUSE_TRACING';
export const START_SLOW_CALLS_TRACING = 'START_SLOW_CALLS_TRACING';
export const STOP_SLOW_CALLS_TRACING = 'STOP_SLOW_CALLS_TRACING';
// ?
export const CAPTURE_DATA = 'CAPTURE_DATA';
export const CAPTURE_CALLS = 'CAPTURE_CALLS';
