export const STATUS = {
  RUNNING: 'running',
  PAUSED: 'paused',
  INIT: 'initialized',
  OVERFLOW: 'overflow',
};
export const SPEC = {
  ALL: 'all',
  PAUSE: 'pause',
};
export const CAPTURE_CALLS_ACTION = {
  APP_INITIALIZATION: 'APP_INITIALIZATION',
  START_FIRST_CALLS_CAPTURE: 'START_FIRST_CALLS_CAPTURE',
  START_NEXT_CALLS_CAPTURE: 'START_NEXT_CALLS_CAPTURE',
  CAPTURING: 'CAPTURING',
  LAST_CALLS_CAPTURE: 'LAST_CALLS_CAPTURE',
};
export const THRESHOLD_LIMIT = 1000000;
export const CALLS_LIMIT = 100;
