name: CI

on:
  pull_request:
  push:
    branches:
      - 'github_actions'
      - 'master'

jobs:
  test:
    name: OTP ${{ matrix.otp_version }}
    runs-on: ubuntu-latest
    container: erlang:${{ matrix.otp_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - otp_version: 29
          erl_hist: true
          run_dialyzer: true

        - otp_version: 28
          erl_hist: true

        - otp_version: 27
          erl_hist: true

        - otp_version: 26
          # hdr_histogram NIF requires the below PR to be merged to build on OTP 26
          # https://github.com/HdrHistogram/hdr_histogram_erl/pull/44
          erl_hist: true

        - otp_version: 25

        - otp_version: 24
          send_coverage: true

    steps:
    - uses: actions/checkout@v3

    - if: matrix.erl_hist
      run: echo "XPROF_ERL_HIST=true" >> $GITHUB_ENV

    - name: Cache hex packages
      uses: actions/cache@v3
      with:
        path: $HOME/.cache/rebar3
        key: ${{ matrix.otp_version }}-rebar3-cache

    - run: make test

    - if: matrix.run_dialyzer
      run: make dialyzer
      timeout-minutes: 8

    - if: matrix.send_coverage && success()
      run: make send_coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

  test_json_lib:
    name: Test different json lib (${{ matrix.json_lib }} | OTP ${{ matrix.otp_version }})
    runs-on: ubuntu-latest

    container: erlang:${{ matrix.otp_version }}

    strategy:
      fail-fast: false
      matrix:
        otp_version: [24]
        json_lib: [jiffy, jsx, thoas]

    steps:
    - uses: actions/checkout@v3

    - name: Cache hex packages
      uses: actions/cache@v3
      with:
        path: $HOME/.cache/rebar3
        key: ${{ matrix.otp_version }}-rebar3-cache-json-lib

    - run: make test_${{ matrix.json_lib }}

  test_docs:
    name: Test generating documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: 1.18.x
            otp_version: 27
            rebar3: '3.24.0'
            # hdr_histogram NIF requires the below PR to be merged to build on OTP 26
            # https://github.com/HdrHistogram/hdr_histogram_erl/pull/44
            erl_hist: true

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp_version}}
        elixir-version: ${{matrix.elixir}}
        rebar3-version: ${{matrix.rebar3}}

    - if: matrix.erl_hist
      run: echo "XPROF_ERL_HIST=true" >> $GITHUB_ENV

    - name: Cache hex packages
      uses: actions/cache@v3
      with:
        path: $HOME/.cache/rebar3
        key: ${{ matrix.otp_version }}-rebar3-cache

    - run: make gen_ex_doc

  test_elixir:
    name: Test with Elixir (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp_version}})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.4
            otp_version: 24
            rebar3: '3.18.0'
            os: ubuntu-latest

          - elixir: 1.12.x
            otp_version: 24
            rebar3: '3.19.0'
            os: ubuntu-latest

          - elixir: 1.13.x
            otp_version: 24
            rebar3: '3.20.0'
            os: ubuntu-latest

          - elixir: 1.14.x
            otp_version: 25
            rebar3: '3.21.0'
            os: ubuntu-latest

          - elixir: 1.15.x
            otp_version: 26
            rebar3: '3.22.1'
            # hdr_histogram NIF requires the below PR to be merged to build on OTP 26
            # https://github.com/HdrHistogram/hdr_histogram_erl/pull/44
            erl_hist: true
            os: ubuntu-latest

          - elixir: 1.16.x
            otp_version: 26
            rebar3: '3.23.0'
            erl_hist: true
            os: ubuntu-latest

          - elixir: 1.17.x
            otp_version: 27
            rebar3: '3.23.0'
            erl_hist: true
            os: ubuntu-latest

          - elixir: 1.18.x
            otp_version: 27
            rebar3: '3.24.0'
            erl_hist: true
            os: ubuntu-latest

          - elixir: 1.19.x
            otp_version: 28
            rebar3: '3.25.1'
            erl_hist: true
            os: ubuntu-latest

          - elixir: 1.20.x
            otp_version: 29
            rebar3: '3.27.0'
            erl_hist: true
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp_version}}
        elixir-version: ${{matrix.elixir}}
        rebar3-version: ${{matrix.rebar3}}

    - if: matrix.erl_hist
      run: echo "XPROF_ERL_HIST=true" >> $GITHUB_ENV

    - name: Cache hex packages
      uses: actions/cache@v3
      with:
        path: $HOME/.cache/rebar3
        key: ${{ matrix.otp_version }}-rebar3-cache

    - run: make test

  test_front_end:
    name: Test front-end
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '8'

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: apps/xprof_gui/priv/node_modules
        key: test_front_end

    - run: make bootstrap_front_end

    - run: make test_front_end
